//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   CREATE TABLE tbl_data (
        ///	id INTEGER NOT NULL,
        ///	val1 INTEGER,
        ///	val2 VARCHAR(50),
        ///	PRIMARY KEY (id)
        ///)
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableDataChange {
            get {
                return ResourceManager.GetString("CreateTableDataChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE tbl_remuneration (
        ///	id INTEGER NOT NULL,
        ///	staff_id INTEGER,
        ///	payment_date VARCHAR(50),
        ///	money DECIMAL,
        ///	PRIMARY KEY (id)
        ///)
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableRemuneration {
            get {
                return ResourceManager.GetString("CreateTableRemuneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE tbl_staff (
        ///	id INTEGER NOT NULL,
        ///	name VARCHAR(50),
        ///	PRIMARY KEY (id)
        ///)
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableStaff {
            get {
                return ResourceManager.GetString("CreateTableStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   INSERT INTO tbl_remuneration (id, staff_id, payment_date, money) VALUES({0}, {1}, {2}, {3}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InsertTableRemuneration {
            get {
                return ResourceManager.GetString("InsertTableRemuneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   INSERT INTO tbl_staff (id, name) VALUES({0}, {1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InsertTableStaff {
            get {
                return ResourceManager.GetString("InsertTableStaff", resourceCulture);
            }
        }
    }
}
